import jsPDF from 'jspdf'
import type { FilmScene } from '../data/a24-scenes'
import type { Collection } from './collections'
import { getCollectionScenes } from './collections'

export async function exportCollectionToPDF(
  collection: Collection,
  allScenes: FilmScene[]
): Promise<void> {
  const scenes = getCollectionScenes(collection.id, allScenes)

  if (scenes.length === 0) {
    alert('No frames in this collection to export')
    return
  }

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = 210
  const pageHeight = 297
  const margin = 20
  const contentWidth = pageWidth - (margin * 2)

  // Title page
  pdf.setFontSize(24)
  pdf.setFont('helvetica', 'bold')
  pdf.text(collection.name, margin, margin + 10)

  if (collection.description) {
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'normal')
    const descLines = pdf.splitTextToSize(collection.description, contentWidth)
    pdf.text(descLines, margin, margin + 20)
  }

  pdf.setFontSize(10)
  pdf.setTextColor(128)
  pdf.text(
    `${scenes.length} frames • Created ${new Date(collection.createdAt).toLocaleDateString()}`,
    margin,
    margin + (collection.description ? 40 : 25)
  )

  pdf.setTextColor(0)

  // CineBox branding
  pdf.setFontSize(8)
  pdf.setTextColor(128)
  pdf.text('Generated by CineBox', margin, pageHeight - 10)
  pdf.setTextColor(0)

  // Add scenes
  let yPosition = margin + (collection.description ? 55 : 40)
  let sceneCount = 0

  for (const scene of scenes) {
    // Check if we need a new page
    if (yPosition > pageHeight - 80 && sceneCount > 0) {
      pdf.addPage()
      yPosition = margin
    }

    try {
      // Load and add image
      const img = await loadImage(scene.url)
      const imgWidth = contentWidth
      const imgHeight = (imgWidth * 9) / 16 // 16:9 aspect ratio

      // Add image
      pdf.addImage(img, 'JPEG', margin, yPosition, imgWidth, imgHeight)

      // Add metadata below image
      yPosition += imgHeight + 5

      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'bold')
      pdf.text(scene.film, margin, yPosition)

      pdf.setFontSize(9)
      pdf.setFont('helvetica', 'normal')
      pdf.setTextColor(80)
      pdf.text(
        `${scene.director} • ${scene.year} • ${scene.studio}`,
        margin,
        yPosition + 5
      )

      // Visual tags
      const tags = [
        ...scene.tags.composition.slice(0, 2),
        ...scene.tags.color.slice(0, 2),
        ...scene.tags.mood.slice(0, 2)
      ].join(', ')

      pdf.setFontSize(8)
      pdf.text(tags, margin, yPosition + 10)

      pdf.setTextColor(0)

      yPosition += 20
      sceneCount++
    } catch (error) {
      console.error(`Failed to load image for ${scene.film}:`, error)
      // Continue with next scene even if one fails
    }
  }

  // Save PDF
  const filename = `${collection.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_moodboard.pdf`
  pdf.save(filename)
}

function loadImage(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.crossOrigin = 'anonymous'

    img.onload = () => {
      const canvas = document.createElement('canvas')
      canvas.width = img.width
      canvas.height = img.height

      const ctx = canvas.getContext('2d')
      if (!ctx) {
        reject(new Error('Failed to get canvas context'))
        return
      }

      ctx.drawImage(img, 0, 0)

      try {
        const dataUrl = canvas.toDataURL('image/jpeg', 0.8)
        resolve(dataUrl)
      } catch (error) {
        reject(error)
      }
    }

    img.onerror = () => {
      reject(new Error(`Failed to load image: ${url}`))
    }

    img.src = url
  })
}

export async function exportSceneToPDF(scene: FilmScene): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = 297
  const pageHeight = 210
  const margin = 20

  try {
    // Load and add image
    const img = await loadImage(scene.url)
    const imgWidth = pageWidth - (margin * 2)
    const imgHeight = (imgWidth * 9) / 16

    const yPos = (pageHeight - imgHeight) / 2

    pdf.addImage(img, 'JPEG', margin, yPos, imgWidth, imgHeight)

    // Add metadata at bottom
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'bold')
    pdf.text(scene.film, margin, pageHeight - 20)

    pdf.setFontSize(9)
    pdf.setFont('helvetica', 'normal')
    pdf.setTextColor(80)
    pdf.text(
      `${scene.director} • ${scene.year} • ${scene.studio}`,
      margin,
      pageHeight - 14
    )

    pdf.setFontSize(7)
    pdf.text('Generated by CineBox', pageWidth - margin - 40, pageHeight - 10)

    const filename = `${scene.film.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_frame.pdf`
    pdf.save(filename)
  } catch (error) {
    console.error('Failed to export scene to PDF:', error)
    alert('Failed to export. The image may not be accessible.')
  }
}
